# -*- coding: utf-8 -*-
"""Week4_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TWj3kbOzmWfmQJbKBYFBYLFZfQDPO24i
"""

intents={

         "greetings":{
             "patterns":["hi","hello","hey"],
             "responses":["Hello!!","Hi there","heyy"]
         },
         "price_query":{
             "patterns":["price","cost","rate"],
             "responses":["Please tell me the commodity name"]
         },
         "goodbye":{
             "patterns":["bye","exit"],
             "responses":["Goodbye!","See you later!"]
         }
}
#i have added two new category fruits and vegetables
vegetables={"potato":{"price":"40 rupees/kg"},
            "onion":{"price":"35 rupees/kg"},
            "tomato":{"price":"30 rupees/kg"},
            "carrot":{"price":"50 rupees/kg"},
          }
fruits={"apple":{"price":"100 rupees/kg"},
        "banana":{"price":"50 rupees/kg"},
        "orange":{  "price":"70 rupees/kg"},
        "grapes":{"price":"80 rupees/kg"}}

#to get the random choices in pattern and responses
import random
# function to detect the intents
def get_intent(user_input):
    user_input = user_input.lower()

# range works with list and items works with dictionary
    for intent, data in intents.items():
        for pattern in data["patterns"]:
            if pattern in user_input:
                return intent

    return "Unknown"

#to fetch the vegetables
def get_vegetables(user_input):
    user_input = user_input.lower()
#it will return the vegetable name if available in the vegetables dictionary
    for vegetable, variety in vegetables.items():
        if vegetable in user_input:
            return vegetable

    return "Not Available"

#to fetch the fruits
def get_fruits(user_input):
    user_input = user_input.lower()
 #this is used to return the fruits if available
    for fruit, varieties in fruits.items():
        if fruit in user_input:
            return fruit

    return "NA"


# function for chatbot
def chatbot():
    while True:
        user_input = input("User: ")

        intent = get_intent(user_input)

        # to check the price of vegetables
        vegetable = get_vegetables(user_input)
        if vegetable != "Not Available":
            print(f"Bot: Price of {vegetable} is ", vegetables[vegetable]["price"])
            continue

        # to check price of fruit
        fruit = get_fruits(user_input)
        if fruit != "NA":
            print(f"Bot: Price of {fruit} is ", fruits[fruit]["price"])
            continue

        # THEN handle intents
        if intent == "Unknown":
            print("Bot: I didn't understand.")
        else:
            print("Bot:", random.choice(intents[intent]["responses"]))

        if intent == "goodbye":
            break

chatbot()